#version 450

/*layout(local_size_x_id = 0, local_size_y = 1, local_size_z = 1) in;

layout(binding = 0, rgba8ui) uniform uimage2D outputPyramid;

layout(constant_id = 1) const uint totalSize = 0;

void main() {
    uint idx = gl_GlobalInvocationID.x;
    if (idx < totalSize) {
        ivec2 coord = ivec2(idx % imageSize(outputPyramid).x, idx / imageSize(outputPyramid).x);
        imageStore(outputPyramid, coord, uvec4(0));
    }
}*/
layout(local_size_x_id = 0) in;

layout(std430, binding = 0) buffer LevelBuffer {
    int currentLevel[];
};

layout(constant_id = 1) const uint set_level = 0;
layout(constant_id = 2) const uint totalSize = 0;

void main() {
    uint idx = gl_GlobalInvocationID.x;
    if (idx < totalSize) {
        currentLevel[idx] = int(set_level);
    }
}